package.json, src/app/(app)/chatbot/page.js
=> fix: 챗봇 수정

src/app/(app)/m/store-select/page.js
=> fix 프론트 store-select /무인매장 선택하기(view type로직변경)

src/components/chart/BestProduct.js, src/components/chart/CategoryGraph.js, src/components/chart/GenderVisitor.js, src/components/chart/SalesGraph.js, src/components/chart/VisitorGraph.js
차트를 React Component로 바꾼것 때문에 GenderVisitor의 기본 값 색상이 안 나와서 직접 지정
=> fix: 기존 canvas로 만든 차트의 위치를 위로 올리기 위해 React Chart Component로 변경

src/components/chart/GenderVisitor.js, src/components/chart/SalesGraph.js
색상 투명도, 일일 매출 그래프 채우기색 안 나오는 것 수정
=> fix: 일일 매출 현황에 fill 색상 안나오는 것 수정

src/app/(app)/m/chatbot/page.js
=> fix: 챗봇 로고 수정

src/app/(web-no-nav)/login/admin/page.js, src/app/(web-no-nav)/login/store/page.js
=> fix: 회원가입 버튼 추가

src/app/(web-no-nav)/register/page.js
=> fix: 사업자 회원가입 버튼 크기조정 및 색상 수정

src/app/(app)/mobile/login/page.js
=> fix: 버튼 크기 수정 및 소셜로그인 오류 해결

src/app/(web-no-nav)/login/admin/page.js, src/app/(web-no-nav)/login/store/page.js
=> fix: admin store로그인 경고창 유효성검사

src/app/(app)/m/chatbot/page.js
=> fix: STT무한 로딩 수정

src/app/(app)/m/chatbot/page.js
=> fix: chatbot 전송 수정

src/app/(app)/m/chatbot/page.js
=> fix: 버튼클릭 수정

src/app/(app)/m/store-select/camera/[storeId]/page.js
=> fix: 뒤로가기 버튼 생성

src/components/CartNavbar.js
=> fix: 버튼 색상 수정

src/app/(app)/m/chatbot/page.js
=> fix: 채팅위치 수정

src/app/(app)/m/chatbot/page.js
=> fix: 버튼 클릭수정 제발 좀 돼라

src/app/(app)/m/chatbot/page.js
=> fix: 안쓰는거 삭제

src/app/(app)/m/chatbot/page.js
=> fix: 위치허용 오류 해결

src/app/(app)/m/chatbot/page.js
=> fix: 음성인식 계속 켜져있는 오류 수정

src/app/(app)/m/order-history/page.js, src/app/(app)/m/point/page.js, src/app/(app)/m/store-select/page.js
=> fix: 글자 크기 수정

src/app/(app)/m/chatbot/page.js
=> fix: 챗봇 출력방법 변경

src/app/(app)/mobile/login/page.js
=> fix: 소셜로그인 수정

src/app/(app)/m/chatbot/page.js
=> fix: 무한 음성인식 해결
